def Employees():
    employees=[
        {
            'id':1,
            'name':'Riya',
            'age':24,
            'salary':30000
        },
        {
            'id':2,
            'name':'Ashitha',
            'age':27,
            'salary':45000
        },
        {
            'id':3,
            'name':'Riya',
            'age':24,
            'salary':45000
        },
        {
            'id':4,
            'name':'Fathima',
            'age':27,
            'salary':30000
        },
        {
            'id':5,
            'name':'Anisha',
            'age':30,
            'salary':47000
        },
        {
            'id':6,
            'name':'Sourav',
            'age':22,
            'salary':30000
        },
        {
            'id':7,
            'name':'Pranav',
            'age':26,
            'salary':40000
        },
        {
            'id':8,
            'name':'Rafel',
            'age':29,
            'salary':30000
        },
        {
            'id':9,
            'name':'Anu',
            'age':20,
            'salary':28000
        }
    ]
    return employees